#!/usr/bin/env python3

import subprocess

def run_server():
    """Run the HTTP server script."""
    return subprocess.Popen(["python3", "backend/server.py"])


if __name__ == '__main__':
    # Start both servers
    server_process = run_server()

    print("The server has been started.")

    # Wait for both servers to complete
    try:
        server_process.wait()
    except KeyboardInterrupt:
        # Handle the interrupt signal and terminate the processes gracefully
        print("Shutting down both servers...")
        server_process.terminate()
